### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by Codebryo** [itsthatguy/atom-itg-flat#2]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `itg-flat-dark` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:430:9)
ThemePackage.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:441:32)
ThemePackage.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:423:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:47:19)
```

**Comment by itsthatguy** [comment]
@Codebryo could you make a pull request to resolve this?

**Comment by Codebryo** [comment]
I will probably try to do that :D

**Comment by daverogers** [comment]
I'm still seeing this error, I think the change needs to be published to Atom's package repo...

https://atom.io/docs/v0.74.0/publishing-a-package

![screen shot 2015-06-15 at 2 10 21 pm](https://cloud.githubusercontent.com/assets/953524/8170828/51899b90-1368-11e5-8002-149de3e96153.png)

**Comment by Codebryo** [comment]
Sry somehow I didn't yet had time to go through with all the changes
completely. I will try to do that asap and make the PR. :/

Dave Rogers <notifications@github.com> schrieb am Mo., 15. Juni 2015 um
23:12 Uhr:

**Comment by itsthatguy** [comment]
awesome!

**Comment by itsthatguy** [comment]
@Codebryo oooorrrr.... https://github.com/itsthatguy/atom-itg-flat/pull/4/files

**Comment by itsthatguy** [comment]
can we consider this closed?

**Comment by daverogers** [comment]
Yes, this can be closed. I got ya @Codebryo ;)

**Comment by itsthatguy** [comment]
#published
